### ISSUE TITLE
Grey out the Shutdown option if no running Terminals

### ISSUE THREAD

**Issue by willingc** [jtpio/jupyterlab-classic#48]
This is a small UI suggestion. Grey out the `Shut Down All` option if none are running.

@jtpio This is amazing work!!!!

**Comment by jtpio** [comment]
Thanks!!

This is probably something that can be addressed in JupyterLab directly, since JupyterLab Classic reuses the same component as is:

![image](https://user-images.githubusercontent.com/591645/102128339-022ff280-3e4e-11eb-9a54-be99f41bf2f2.png)

**Comment by jtpio** [comment]
Fixed in https://github.com/jupyterlab/jupyterlab/pull/9468

Should be available in JupyterLab Classic after updating to the JupyterLab RC packages and cutting a new release for `jupyterlab-classic`.
