### ISSUE TITLE
Focus issue after command palette

### ISSUE THREAD

**Issue by Carreau** [jtpio/jupyterlab-classic#51]
In a notebook
- create code cell
- Ctrl-Shift-C for command palette
   - Change cell type to markdown
   - Enter
- Focus is now lost, and there does not seem to be any way to get it back using only the keyboard.

**Comment by jtpio** [comment]
Thanks @Carreau.

Just checked and this doesn't seem to be an issue in JupyterLab, as hitting enter brings the focus back on the notebook.

**Comment by Carreau** [comment]
Seem to be the case also if you rename; then the focus is nowhere. 
Might be more difficult to figure out what to do as for rename the user actually have clicked on on the notebook name.

**Comment by jtpio** [comment]
The focus issue after renaming the file also seems to be in JupyterLab.

I opened https://github.com/jtpio/jupyterlab-classic/pull/54 to fix these two cases. But there might be more instances of this behavior.
