### ISSUE TITLE
Incompatible versions on install

### ISSUE THREAD

**Issue by astrojuanlu** [jtpio/jupyterlab-classic#56]
I tried installing jupyterlab-classic (thanks for this project, looks awesome!) using this `requirements.in` file for pip-tools:

```
$ cat requirements.in 
jupyterlab-classic~=0.1.0rc1
```

and got this error:

```
Could not find a version that matches jupyter-server~=1.0.1,~=1.1 (from jupyterlab==3.0.0rc13->jupyterlab-classic==0.1.0rc1->-r requirements.in (line 1))
Tried: 0.0.1, 0.0.1, 0.0.2, 0.0.2, 0.0.3, 0.0.3, 0.0.4, 0.0.4, 0.0.5, 0.0.5, 0.1.0, 0.1.0, 0.1.1, 0.1.1, 0.2.0, 0.2.0, 0.2.1, 0.2.1, 0.3.0, 0.3.0, 1.0.0, 1.0.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.0.3, 1.0.3, 1.0.4, 1.0.4, 1.0.5, 1.0.5, 1.0.6, 1.0.6, 1.0.7, 1.0.7, 1.0.8, 1.0.8, 1.0.9, 1.0.9, 1.0.10, 1.0.10, 1.0.11, 1.0.11, 1.1.0, 1.1.0, 1.1.1, 1.1.1
Skipped pre-versions: 1.0.0rc0, 1.0.0rc0, 1.0.0rc1, 1.0.0rc1, 1.0.0rc2, 1.0.0rc2, 1.0.0rc3, 1.0.0rc3, 1.0.0rc4, 1.0.0rc4, 1.0.0rc5, 1.0.0rc5, 1.0.0rc6, 1.0.0rc6, 1.0.0rc7, 1.0.0rc7, 1.0.0rc8, 1.0.0rc8, 1.0.0rc9, 1.0.0rc9, 1.0.0rc10, 1.0.0rc10, 1.0.0rc11, 1.0.0rc11, 1.0.0rc12, 1.0.0rc12, 1.0.0rc13, 1.0.0rc13, 1.0.0rc14, 1.0.0rc14, 1.0.0rc15, 1.0.0rc15, 1.0.0rc16, 1.0.0rc16
There are incompatible versions in the resolved dependencies:
  jupyter-server~=1.1 (from nbclassic==0.2.5->jupyterlab==3.0.0rc13->jupyterlab-classic==0.1.0rc1->-r requirements.in (line 1))
  jupyter-server~=1.1.0 (from jupyterlab-server==2.0.0rc9->jupyterlab==3.0.0rc13->jupyterlab-classic==0.1.0rc1->-r requirements.in (line 1))
  jupyter-server~=1.0.1 (from jupyterlab==3.0.0rc13->jupyterlab-classic==0.1.0rc1->-r requirements.in (line 1))
```

I guess this is not really a jupyterlab-classic issue, but I am unsure on how to proceed from here, or where to report this.

**Comment by jtpio** [comment]
Thanks @astrojuanlu for reporting this.

Can you confirm that running `pip install jupyterlab-classic~=0.1.0rc1` in a new environment proceeds correctly with the installation? Just to check whether this has to do with pip-tools.

**Comment by astrojuanlu** [comment]
Indeed, this works, even if using the new pip dependency resolver. And `pip check` does not show any broken requirement. Therefore this looks like a pip-tools issue...?

Feel free to close this one, I might open a new issue on pip-tools when I have the time.

**Comment by jtpio** [comment]
Thanks for checking.

`nbclassic` recently switched to `jupyter-server~=1.1` (in `0.2.5`), while `jupyterlab==3.0.0rc13` is still on `jupyter-server~=1.0.1`. So that might be the reason.

Once `jupyterlab==3.0.0rc14` is out (which will depend on ``jupyter-server~=1.1``), I'll cut a new rc for `jupyterlab-classic` too so it depends on the latest packages. Hopefully that should help with this.

**Comment by astrojuanlu** [comment]
jupyterlab 3.0.0rc14 was published 8 hours ago, and this error can't be reproduced anymore with it. Besides, I opened an issue on pip-tools. Closing this, and thanks for your prompt response!

**Comment by jtpio** [comment]
Nice, yes that makes sense.

Thanks!
