### ISSUE TITLE
relation with jupyter ecosystem

### ISSUE THREAD

**Issue by ananis25** [jtpio/jupyterlab-classic#57]
I apologize if this is not the right place to ask. I saw the project link on twitter, but couldn't confirm where the Jupyterlab classic extension stands wrt Jupyter lab/notebook. Is this description of the different tools correct? 

Chronologically, 
1. Jupyter notebook - classic frontend, classic notebook server. 
2. Jupyter lab - jupyterlab frontend, classic notebook server. Extensions needed a nodejs install, not always compatible with classic notebook.
3. Jupyter lab 3.0 - jupyterlab frontend, new jupyter server. Extensions can be installed with pip.
4. nbclassic - classic frontend, new jupyter server. Unsure about extensions. 
5. jupyterlab-classic - *classic-like* frontend built with jupyterlab components, otherwise same as Jupyter lab 3.0.

The Jupyter lab frontend + extension experience wasn't very convenient, so I have still kept using 1. The new extension seems like the best of both worlds, so very excited to try it. Thanks for the work this!

**Comment by jtpio** [comment]
Thanks @ananis25, this is the right place!

The first thing to notice is that JupyterLab Classic is a bit more than just an extension. It's an alternative frontend, but reusing a lot of existing JupyterLab components. So a bit like reassembling JupyterLab from the ground-up but in a different way.

> Chronologically,
> 
>     1. Jupyter notebook - classic frontend, classic notebook server.
> 
>     2. Jupyter lab - jupyterlab frontend, classic notebook server. Extensions needed a nodejs install, not always compatible with classic notebook.
> 
>     3. Jupyter lab 3.0 - jupyterlab frontend, new jupyter server. Extensions can be installed with pip.
> 
>     4. nbclassic - classic frontend, new jupyter server. Unsure about extensions.
> 
>     5. jupyterlab-classic - _classic-like_ frontend built with jupyterlab components, otherwise same as Jupyter lab 3.0.

This is a nice and accurate summary. Maybe it would make sense to add it to the readme to provide more context?

> The Jupyter lab frontend + extension experience wasn't very convenient, so I have still kept using 1

Is it the lab frontend or the extension experience that you found not very convenient? Or both?

One of the main improvements in JupyterLab 3.0 is the new distribution system for extensions, that don't require a rebuild on the end user side. And JupyterLab Classic uses the same system, which means that extensions distributed that way for 3.0 can be reused in JupyterLab Classic (as long as the components the extension wants to extend are part of this classic interface).

**Comment by ananis25** [comment]
Thank you for clarifying. It is also helpful as an example of making custom frontends while keeping compatibility with the rest of Jupyter lab. For ex, a frontend that does away with notebook files and uses content addressable cells would be really cool for data analysis; I'll definitely try it after gaining necessary javascript chops. 

> Is it the lab frontend or the extension experience that you found not very convenient? Or both?

It has really been both.  For ex - 
* The standard lab interface takes a lot of screen real estate compared to the classic interface. 
* Older notebooks give me a "javascript output is disabled" warning, even for cells without any output. 
```py
[1] a = 10
``` 
* Plotting extensions like bokeh didn't work out of the box, and the corresponding extensions ask for a nodejs/npm install. 

A jupyter notebook to jupyter lab migration guide would've been really helpful. Though it looks like Jupyterlab 3.0 solves these problems, so excited to try it!

**Comment by jtpio** [comment]
Thanks for the feedback :+1: 

>  It is also helpful as an example of making custom frontends while keeping compatibility with the rest of Jupyter lab

Yes hopefully this project can also show how to make your own frontend if you would like too. There is probably still a bit work to do to streamline the build process, but cloning or forking the repo should serve as a good start already. At some point we might even be able to design a WYSIWYG interface to choose the plugins and extensions to include in the custom interface. 

> The standard lab interface takes a lot of screen real estate compared to the classic interface.

This is actually one of the motivation for starting JupyterLab Classic, and is shared by a couple of folks used to focusing on a single notebook at a time.

> Older notebooks give me a "javascript output is disabled" warning, even for cells without any output.

This sounds strange. Maybe there is more info when looking at the notebook in JSON format directly?

> A jupyter notebook to jupyter lab migration guide would've been really helpful

We were recently thinking that JupyterLab Classic could actually be some kind of middle-ground between JupyterLab and the classic frontend.

**Comment by ananis25** [comment]
Thank you for the background on lab, I'll retry and see if the `javascript output` error still comes up. 

I think there are a fair bit of people on the old jupyter notebook, so I created a PR for the readme at #61 .
