### ISSUE TITLE
Provider for jupyterlab/fileeditor:IEditorTracker?

### ISSUE THREAD

**Issue by krassowski** [jtpio/jupyterlab-classic#72]
Hi, I was looking at enabling the jupyterlab-lsp extension to work with classic. I wonder if it would be possible/reasonable to have a provider for `jupyterlab/fileeditor:IEditorTracker`? I see that there is a file editor that derives from the jupyterlab file editor, but it does not seem to expose a tracker at the time of extension loading.

Could it be because of this logic?

https://github.com/jtpio/jupyterlab-classic/blob/f7b5077f48a7b38c3638eb9e999ee098bb006813/builder/index.js#L113-L145

**Comment by jtpio** [comment]
Right, JupyterLab Classic tries to limit the number of loaded plugins and stick to the strict minimum.

But normally the `jupyterlab/fileeditor:IEditorTracker` token should be provided on the file editor page (`/classic/edit`) in JupyterLab Classic:

https://github.com/jtpio/jupyterlab-classic/blob/f7b5077f48a7b38c3638eb9e999ee098bb006813/builder/index.js#L138-L140

Since it's provided by the lab plugin: 

https://github.com/jupyterlab/jupyterlab/blob/7d0d2e45897ede23e5a1acbc095e6c5a05d493fe/packages/fileeditor-extension/src/index.ts#L56-L75

Does `jupyterlab-lsp` need this plugin in other places? Is so maybe it should be made available by default? (and not only for the edit page)

**Comment by krassowski** [comment]
I think no, if it is available on the page with editor then it should be fine. What about `@jupyterlab/completer:ICompletionManager`? on the editor site? Is this intended to not provide completion in file editor and only in notebooks?

**Comment by krassowski** [comment]
After making some plugins optional it does appear promising :) Thank you for all the work here!

For some strange reason I do not receive `IClassicShell` service, but using `app.shell` is good enough!

![Screenshot from 2021-01-10 02-45-21](https://user-images.githubusercontent.com/5832902/104113076-f3721980-52ed-11eb-9e0a-640bd5b1c853.png)

![Screenshot from 2021-01-10 02-48-33](https://user-images.githubusercontent.com/5832902/104113114-5bc0fb00-52ee-11eb-8e26-bc18c09950fb.png)

There are a few things that do not work yet, most notably completion in the file editor. Do you plan to enable completer in the file editor too or should I look for a way to do that from the lsp extension?

**Comment by jtpio** [comment]
> After making some plugins optional it does appear promising :) Thank you for all the work here!

Nice, looking good!

> For some strange reason I do not receive `IClassicShell` service, but using `app.shell` is good enough!

Usually it's good practice to use `app.shell` (a `JupyterFrontEnd.IShell`) as much as possible, and more specific shells like `ILabShell` and `IClassicShell` only when necessary (which can then be made `optional`).

> Do you plan to enable completer in the file editor too or should I look for a way to do that from the lsp extension?

I think we can add it to JupyterLab Classic yes. That means having  these plugins loaded by default (and not only for the notebooks):

https://github.com/jtpio/jupyterlab-classic/blob/57d7000390eebd7457235be2433d364808fc624b/builder/index.js#L123-L127

And probably add the one for the file editors.

Would you like to give it a shot and open a PR? Thanks!

**Comment by krassowski** [comment]
Thank you for the help with this one @jtpio! I will look into the status(bar) item issues over the weekend and hopefully release new LSP extension version by Monday!

**Comment by jtpio** [comment]
Thanks for adding support for JupyterLab Classic!

Just tried from source and it works well!

![image](https://user-images.githubusercontent.com/591645/104512297-47cb1100-55ee-11eb-9c57-273594f9b098.png)
