### ISSUE TITLE
No provider for @jupyterlab/codemirror ICodeMirror

### ISSUE THREAD

**Issue by martinRenou** [jtpio/jupyterlab-classic#77]
When using a custom syntax highlighting extension, I am getting the following error:

```
Error: No provider for: @jupyterlab/codemirror:ICodeMirror.
    at s.e.resolveRequiredService (6731.bundle.js:2)
    at 6731.bundle.js:2
    at Array.map (<anonymous>)
    at s.e.activatePlugin (6731.bundle.js:2)
    at 6731.bundle.js:2
    at Array.map (<anonymous>)
    at s.e.start (6731.bundle.js:2)
    at 880.bundle.js:1
```

**Comment by jtpio** [comment]
Thanks @martinRenou.

It looks like we would need to add the corresponding plugin to the list here to make it available:

https://github.com/jtpio/jupyterlab-classic/blob/17e7b596281cdf77d486f8e9864ac9d63bb7a7ed/builder/index.js#L90-L92
