### ISSUE TITLE
Feedback UI: document title

### ISSUE THREAD

**Issue by chmp** [jtpio/jupyterlab-classic#99]
Thanks a lot for this great project. It made me finally switch from the classic notebook. One thing I noticed while using jupyterlab-classic, was that the table title is always "Jupyterab Classic - Notebook". I often have multiple notebooks open at the same time. With this setup having the Notebook name in the title would help a lot.

**Comment by jtpio** [comment]
Thanks @chmp.

This sounds good, it makes sense to put the name of the notebook in the title :+1: 

Additionally the classic notebook also changes the favicon depending on the page (notebook / files):

![image](https://user-images.githubusercontent.com/591645/106866261-883d1c80-66cc-11eb-8252-0cb4b3a8cbc0.png)

JupyterLab Classic could also do something similar.
